### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [hale4029/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [ ] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
@hale4029  good work on the top down design portion of this. We'd like you to create another class and example object file before we consider you `technical ready`

We want you to make a class_3 file and class_3_example_object file
Keep things simple. For this 3rd class and its example object: 
* [x] Only have 5 attributes and 4 methods 
* [x] Don't use any arrays or hashes
* [x] Do not name attributes in present participle tense (-ing) (ie. `garnished` is a better boolean name than `garnishing`)
* [x] Make sure that your methods don't use any conditional logic and that they:
  * [x] have names that indicate actions
  * [x] change an attribute's value or return information pulled from an attribute(s). 

We need a tangible return value from a method. Let's look at how we could take one of the methods from your class 2 and do that.
ie.
```
Your method:
send_ticket_garnish (if Garnishing = True, then send array of ingredients to garnishing table)
send_ticket_garnish = garnish table

In this case, "garnish table" is an idea that probably involves some steps we can't describe using basic data types, it is not a changed attribute value, or valid data being returned. Make sure that your methods do return something or change an attribute value

An example of it meeting the above requirement:
garnish_dish: (changes garnished attribute from false to true)
garnish_dish: garnished = true
```
